services:
  - type: web
    name: langchain-translate-api
    env: python
    region: oregon  # 필요시 'singapore', 'frankfurt' 등으로 변경
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "uvicorn server:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      - key: DB_CONNECTION_STRING
        value: postgresql://your_user:your_password@your_host:5432/chat_db
    plan: free  # 또는 starter
